jobs:
  - job: Formatting
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        cd $HOME
        mkdir -p $HOME/.ghcup/bin && curl https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > $HOME/.ghcup/bin/ghcup && chmod +x $HOME/.ghcup/bin/ghcup
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        ghcup install 8.6.5
        ghcup set 8.6.5
        ghcup install-cabal
        cabal v2-update
        cabal v2-install ormolu
      displayName: 'Install ormolu'
    - script: |
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        FILES=$(find lib src -name "*.hs")
        echo "Checking files:"
        echo $FILES
        ormolu -c --mode check $FILES
      displayName: 'Check formatting'
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get install libgtk-3-dev
        mkdir -p $HOME/.ghcup/bin && curl https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > $HOME/.ghcup/bin/ghcup && chmod +x $HOME/.ghcup/bin/ghcup
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        ghcup install 8.6.5
        ghcup set 8.6.5
        ghcup install-cabal
        cabal v2-update
      displayName: 'Prepare system'
    - script: |
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        cabal v2-build
        cabal v2-exec -- which foundry hask
      displayName: 'Build'
  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - script: |
        brew install gtk+3 libffi pkgconfig
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
        mkdir -p $HOME/.ghcup/bin && curl https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > $HOME/.ghcup/bin/ghcup && chmod +x $HOME/.ghcup/bin/ghcup
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        ghcup install 8.6.5
        ghcup set 8.6.5
        ghcup install-cabal
        cabal v2-update
      displayName: 'Prepare system'
    - script: |
        export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
        cabal v2-build
        cabal v2-exec -- which foundry hask
      displayName: 'Build'
