name: CI
on:
  pull_request:
  push:
      branches: ["master"]

jobs:
  check:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v2

      - name: Check Nix flake
        run: nix flake check -L

      - name: Build Nix flake
        run: nix build
